// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var Curry = require("bs-platform/lib/js/curry.js");

var dateInDdMmYyyy = (function () {
  const o_date = new Intl.DateTimeFormat();
  const f_date = (m_ca, m_it) => Object({ ...m_ca, [m_it.type]: m_it.value });
  const { day, month, year } = o_date.formatToParts().reduce(f_date, {});
  return day + "/" + month + "/" + year;
});

Curry._1(dateInDdMmYyyy, undefined);

Fs.readFile("./bsconfig.json", "utf8", (function (error, data) {
        if (error == null) {
          console.log("[bsconfig.json]", data);
        } else {
          console.error("config file errro: ", error);
        }
        
      }));

var pathToSomeFile = __dirname + "/bsconfig.json";

console.log((Fs.readFileSync(pathToSomeFile, "utf-8"), undefined));

var pathToHelloTxt = Path.resolve(__dirname, "hello.txt");

var counter = {
  contents: 0
};

function setCounter(step) {
  counter.contents = counter.contents + step | 0;
  
}

setCounter(1);

setCounter(2);

setCounter(3);

setCounter(4);

exports.dateInDdMmYyyy = dateInDdMmYyyy;
exports.pathToSomeFile = pathToSomeFile;
exports.pathToHelloTxt = pathToHelloTxt;
exports.counter = counter;
exports.setCounter = setCounter;
/*  Not a pure module */
