// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SimpleTest = require("./simpleTest.bs.js");

function linkTo(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

var GithubProject__WithoutInterface = {
  linkTo: linkTo
};

var atom = {
  name: "Atom",
  url: "https://atom.io",
  repositories: 255,
  people: 56
};

linkTo(atom);

function url(t) {
  return t.url;
}

function linkTo$1(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

var GithubProject = {
  linkTo: linkTo$1,
  url: url
};

var node = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 182,
  people: 375
};

linkTo$1(node);

var node2 = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 182,
  people: 385
};

var node3 = {
  name: "Node.js",
  url: "https://nodejs.org",
  repositories: 183,
  people: 385
};

SimpleTest.assertEqual("https://nodejs.org", "https://nodejs.org", "[exercise 3] github project url");

function make(name, url, repositories, people) {
  return {
          name: name,
          url: url,
          repositories: repositories,
          people: people
        };
}

function linkTo$2(t) {
  return "<a href=\"" + t.url + "\">" + t.name + "</a>";
}

function name(t) {
  return t.name;
}

function url$1(t) {
  return t.url;
}

function repositories(t) {
  return t.repositories;
}

function people(t) {
  return t.people;
}

function updatePeople(t, count) {
  return {
          name: t.name,
          url: t.url,
          repositories: t.repositories,
          people: t.people + count | 0
        };
}

function updateRepositories(t, count) {
  return {
          name: t.name,
          url: t.url,
          repositories: t.repositories + count | 0,
          people: t.people
        };
}

var GithubProject__OpaqueType = {
  make: make,
  linkTo: linkTo$2,
  name: name,
  url: url$1,
  repositories: repositories,
  people: people,
  updatePeople: updatePeople,
  updateRepositories: updateRepositories
};

var rails = {
  name: "Ruby on Rails",
  url: "https://rubyonrails.org",
  repositories: 99,
  people: 66
};

linkTo$2(rails);

updatePeople(rails, 5);

var rails2 = updateRepositories(rails, 1);

var Github_WI;

var bookFormat = /* Paperback */1;

var Github_OT;

exports.GithubProject__WithoutInterface = GithubProject__WithoutInterface;
exports.Github_WI = Github_WI;
exports.atom = atom;
exports.bookFormat = bookFormat;
exports.GithubProject = GithubProject;
exports.node = node;
exports.node2 = node2;
exports.node3 = node3;
exports.GithubProject__OpaqueType = GithubProject__OpaqueType;
exports.Github_OT = Github_OT;
exports.rails = rails;
exports.rails2 = rails2;
/*  Not a pure module */
